# -*- coding: utf-8 -*-
"""DVP MINI PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AcrYcw0-II7G3iq1EOjzqn68j1N1zhAK
"""

pip install pandas numpy plotly streamlit

# %% [markdown]
# Step 0 — Imports & helper functions
# Run this cell first.

import pandas as pd
import numpy as np
import calendar
from pathlib import Path
import plotly.express as px
import plotly.graph_objects as go

pd.set_option("display.max_columns", 100)

# --- helpers ---
MONTH_ABBR_TO_NUM = {m[:3].upper(): i for i, m in enumerate(calendar.month_name) if m}

def to_month_start(dt_series: pd.Series) -> pd.Series:
    dt = pd.to_datetime(dt_series, errors="coerce", utc=False)
    dt = dt.dt.tz_localize(None, ambiguous='NaT', nonexistent='NaT') if hasattr(dt, "dt") else dt
    return pd.to_datetime(dt.dt.to_period("M").dt.start_time)

def guess_date_col(df: pd.DataFrame):
    cand = [c for c in df.columns if c.lower() in
            {"dt","date","time","timestamp","datetime","formatted date","formatted_date","date_time"}]
    return cand[0] if cand else None

def standardize_country(col: pd.Series) -> pd.Series:
    if col is None:
        return None
    return (col.astype(str)
            .str.strip()
            .str.replace(r"\s+", " ", regex=True)
            .str.title())

def pick_first_existing(df: pd.DataFrame, names):
    for n in names:
        if n in df.columns:
            return n
    return None

def season_from_month(m):
    # Simple India-centric seasons; adjust if needed
    return (
        "Winter" if m in (12,1,2) else
        "Pre-Monsoon" if m in (3,4,5) else
        "Monsoon" if m in (6,7,8,9) else
        "Post-Monsoon"
    )

# %% [markdown]
# Step 1 — Rainfall (India, 1901-2015): melt to monthly, add COUNTRY, DATE

rainfall_path = Path("/content/rainfall in india 1901-2015.csv")
rf = pd.read_csv(rainfall_path)

# drop redundant 'index' if present, normalize cols
if "index" in rf.columns: rf = rf.drop(columns=["index"])
rf.columns = rf.columns.str.strip().str.upper()

# melt months to long
month_cols = ["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"]
have_months = [c for c in month_cols if c in rf.columns]

rf_long = rf.melt(
    id_vars=[c for c in ["SUBDIVISION","YEAR"] if c in rf.columns],
    value_vars=have_months,
    var_name="MONTH",
    value_name="RAINFALL_MM"
)

# fill NaNs subdivision-wise
grp_cols = [c for c in ["SUBDIVISION"] if c in rf_long.columns]
rf_long["RAINFALL_MM"] = rf_long.groupby(grp_cols)["RAINFALL_MM"].transform(
    lambda s: s.fillna(s.mean())
)

# month number & DATE (use first day of month)
rf_long["MONTH_NUM"] = rf_long["MONTH"].map(MONTH_ABBR_TO_NUM).astype(int)
rf_long["DATE"] = pd.to_datetime(
    rf_long["YEAR"].astype(int).astype(str) + "-" + rf_long["MONTH_NUM"].astype(int).astype(str) + "-01"
).dt.to_period("M").dt.start_time

# country column (all India)
rf_long["COUNTRY"] = "India"

# (Optional) aggregate to country-month (sum or mean).
# Rainfall is additive across regions; use mean if you want average rainfall instead.
rf_india = (rf_long
            .groupby(["COUNTRY","DATE"], as_index=False)
            .agg(RAINFALL_MM=("RAINFALL_MM","sum")))

rf_india.head()

# %% [markdown]
# Step 2 — GlobalLandTemperaturesByCountry: monthly AverageTemperature per COUNTRY

glt_path = Path("/content/GlobalLandTemperaturesByCountry.csv")
glt = pd.read_csv(glt_path)

# normalize columns
glt.columns = glt.columns.str.strip().str.title()  # e.g., 'Dt','AverageTemperature','Country'
glt = glt.rename(columns={"Dt":"DATE",
                          "Averagetemperature":"AVG_TEMP_C",
                          "Averagetemperatureuncertainty":"AVG_TEMP_UNC"})

# parse date to month start
glt["DATE"] = to_month_start(glt["DATE"])

# standardize country names
glt["COUNTRY"] = standardize_country(glt["Country"])
glt = glt.drop(columns=["Country"])

# monthly country averages (already monthly, but ensure)
glt_country = (glt
               .groupby(["COUNTRY","DATE"], as_index=False)
               .agg(AVG_TEMP_C=("AVG_TEMP_C","mean"),
                    AVG_TEMP_UNC=("AVG_TEMP_UNC","mean")))

glt_country.head()

import pandas as pd

# Load file to inspect columns
df = pd.read_csv("/content/weather_data_extended.csv")
print(df.columns)
df.head()

# Step 2 — Clean column names
df.columns = [c.strip() for c in df.columns]

# Step 3 — Manually assign correct columns
date_col = "Observation Time"    # date column
country_col = "Location"         # location = country
temp_col = "Temperature (°C)"    # temperature column

# Step 4 — Parse DATE column → roll up to month start
df["DATE"] = pd.to_datetime(df[date_col], errors="coerce").dt.to_period("M").dt.to_timestamp()

# Step 5 — Standardize country column
df["COUNTRY"] = df[country_col]

# Step 6 — Keep only needed columns
df = df[["COUNTRY", "DATE", temp_col]].rename(columns={temp_col: "TEMP_C"})

# Step 7 — Aggregate monthly per country
df_m = (
    df.groupby(["COUNTRY", "DATE"], as_index=False)
      .agg({"TEMP_C": "mean"})
)

df_m.head()

def to_month_start(dt_series):
    """
    Convert a datetime-like series to month start (YYYY-MM-01).
    Handles mixed formats and time zones safely.
    """
    dt = pd.to_datetime(dt_series, errors="coerce", utc=True)  # force UTC
    dt = dt.dt.tz_localize(None)  # drop timezone info
    return dt.dt.to_period("M").dt.to_timestamp()

# %% [markdown]
# Step 4 — OPTIONAL: weatherHistory (often city-level hourly; we monthly-aggregate and tag a country)
# If you don't need it, skip this cell.

from pathlib import Path
import pandas as pd

# --- Helper: safe conversion to month start ---


# --- Helper: pick the first existing column name from a list ---
def pick_first_existing(df, candidates):
    for c in candidates:
        if c in df.columns:
            return c
    return None

# --- Actual Step 4 ---
wh_path = Path("/content/weatherHistory.csv")

if wh_path.exists():
    wh = pd.read_csv(wh_path)
    wh.columns = [c.strip() for c in wh.columns]

    # Try to find a date column
    dcol = pick_first_existing(wh, ["Formatted Date","Formatted_Date","Date","date","datetime"])
    if dcol is None:
        print("⚠️ weatherHistory: date column not found, skipping.")
        wh_m = None
    else:
        # Convert to monthly
        wh["DATE"] = to_month_start(wh[dcol])

        # Try to find a country column; default to "India" if not found
        country_col_wh = pick_first_existing(wh, ["Country","country","COUNTRY"])
        if country_col_wh is None:
            wh["COUNTRY"] = "India"   # adjust if your file is not India
        else:
            wh["COUNTRY"] = wh[country_col_wh]

        # Temperature and rainfall columns
        temp_col_wh = pick_first_existing(wh, ["Temperature (C)","Temperature","Temp","TEMP_C"])
        rain_col_wh = pick_first_existing(wh, ["Precipitation","Rain","Rainfall","PRCP","RAINFALL_MM"])

        # Keep only useful columns
        keep = ["COUNTRY","DATE"]
        if temp_col_wh:
            wh = wh.rename(columns={temp_col_wh:"TEMP_C"})
            keep.append("TEMP_C")
        if rain_col_wh:
            wh = wh.rename(columns={rain_col_wh:"RAINFALL_MM_EXT"})
            keep.append("RAINFALL_MM_EXT")

        # Aggregate monthly
        agg_dict = {}
        if "TEMP_C" in keep:
            agg_dict["TEMP_C"] = "mean"
        if "RAINFALL_MM_EXT" in keep:
            agg_dict["RAINFALL_MM_EXT"] = "sum"

        wh_m = (
            wh[keep]
            .groupby(["COUNTRY","DATE"], as_index=False)
            .agg(agg_dict)
        )

        print("✅ weatherHistory monthly aggregation complete.")
        display(wh_m.head())
else:
    wh_m = None
    print("⚠️ weatherHistory.csv not found — skipping this step.")

# %% [markdown]
# Step 5 — Merge on COUNTRY + DATE; save merged CSV for Tableau

MERGE_HOW = "inner"  # change to "outer" to keep all timelines

df_merged = (glt_country
             .merge(rf_india, on=["COUNTRY","DATE"], how=MERGE_HOW)
             .merge(df_m, on=["COUNTRY","DATE"], how=MERGE_HOW, suffixes=("","_WEX"))
            )

# optionally merge weatherHistory if available
if wh_m is not None:
    df_merged = df_merged.merge(wh_m, on=["COUNTRY","DATE"], how=MERGE_HOW, suffixes=("","_WH"))

# final cleaning
df_merged = df_merged.sort_values(["COUNTRY","DATE"]).reset_index(drop=True)

# Save for Tableau / other tools
out_path = Path("weather_merged_monthly.csv")
df_merged.to_csv(out_path, index=False)

df_merged.head(12)

df_merged.head(12)

# ensure DATE is datetime
# df["DATE"] = pd.to_datetime(df["DATE"]) # No need to convert again

# check unique country names
# print(df["COUNTRY"].unique()) # No need to print

# select India properly from wh_m
country_sel = "India"
if wh_m is not None:
    d1 = wh_m[wh_m["COUNTRY"].str.strip().str.lower() == country_sel.lower()].copy()
else:
    d1 = pd.DataFrame() # Create an empty DataFrame if wh_m is None

print("Rows for India:", len(d1))

# plot temperature
if not d1.empty:
    fig = px.line(
        d1,
        x="DATE",
        y="TEMP_C",   # Use TEMP_C from wh_m
        title=f"Average Temperature — {country_sel} (from weatherHistory.csv)"
    )
    fig.show()
else:
    print(f"No data available to plot for {country_sel}.")

# %% [markdown]
# Viz 2 — Rainfall trend (India) (line)
d2 = rf_india[rf_india["COUNTRY"] == "India"]
fig = px.line(d2, x="DATE", y="RAINFALL_MM", title="Monthly Rainfall — India")
fig.show()

# %% [markdown]
# Viz 3 — Dual-axis: Temp vs Rainfall (India)
# Merge temperature and rainfall data for India
if wh_m is not None:
    temp_india = wh_m[wh_m["COUNTRY"] == "India"].copy()
else:
    temp_india = pd.DataFrame()

rain_india = rf_india[rf_india["COUNTRY"] == "India"].copy()

# Merge the two dataframes on COUNTRY and DATE
d3 = pd.merge(temp_india, rain_india, on=["COUNTRY", "DATE"], how="inner")


if not d3.empty:
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=d3["DATE"], y=d3["TEMP_C"], mode='lines', name='Avg Temp (°C)'))
    fig.add_trace(go.Scatter(x=d3["DATE"], y=d3["RAINFALL_MM"], mode='lines', name='Rainfall (mm)', yaxis="y2"))
    fig.update_layout(
        title="Temperature vs Rainfall — India",
        yaxis=dict(title="Avg Temp (°C)"),
        yaxis2=dict(title="Rainfall (mm)", overlaying='y', side='right')
    )
    fig.show()
else:
    print("No data available to plot Temperature vs Rainfall for India.")

# %% [markdown]
# Viz 4 — Heatmap: Rainfall by Year vs Month (India)
d4 = rf_india[rf_india["COUNTRY"] == "India"].copy()
d4["Year"] = d4["DATE"].dt.year
d4["Month"] = d4["DATE"].dt.month
pivot = d4.pivot_table(index="Year", columns="Month", values="RAINFALL_MM", aggfunc="sum")
fig = px.imshow(pivot, aspect="auto", title="Rainfall Heatmap — India (Year x Month)")
fig.update_xaxes(title="Month")
fig.update_yaxes(title="Year")
fig.show()

import plotly.express as px

# Create decade column
df["Decade"] = (df["DATE"].dt.year // 10) * 10

# Select a valid country
country_sel = "London"   # or "Tokyo", etc.

# Filter data
d5 = df[df["COUNTRY"] == country_sel]

# Create box plot
fig = px.box(
    d5,
    x="Decade",
    y="TEMP_C",
    title=f"Temperature Distribution by Decade — {country_sel}"
)
fig.show()

# %% [markdown]
# Viz 6 — Bar: Total Rainfall by Year (India)
d6 = rf_india[rf_india["COUNTRY"] == "India"].copy()
d6["Year"] = d6["DATE"].dt.year
agg = d6.groupby("Year", as_index=False)["RAINFALL_MM"].sum()
fig = px.bar(agg, x="Year", y="RAINFALL_MM", title="Total Rainfall per Year — India")
fig.show()

# %% [markdown]
# Viz 7 — Scatter: Temp vs Rainfall (India)
# Merge temperature and rainfall data for India
if wh_m is not None:
    temp_india = wh_m[wh_m["COUNTRY"] == "India"].copy()
else:
    temp_india = pd.DataFrame()

rain_india = rf_india[rf_india["COUNTRY"] == "India"].copy()

# Merge the two dataframes on COUNTRY and DATE
d7 = pd.merge(temp_india, rain_india, on=["COUNTRY", "DATE"], how="inner")

if not d7.empty:
    fig = px.scatter(d7, x="TEMP_C", y="RAINFALL_MM", title="Temperature vs Rainfall — India", trendline=None)
    fig.show()
else:
    print("No data available to plot Temperature vs Rainfall scatter plot for India.")

print(df["COUNTRY"].unique())

country_sel = "London"   # or "Tokyo", "Paris", etc.

d8 = df[df["COUNTRY"] == country_sel].copy()
d8["Month"] = d8["DATE"].dt.month
d8["Season"] = d8["Month"].map(season_from_month)

fig = px.strip(
    d8,
    x="Season",
    y="TEMP_C",
    color="Season",
    title=f"Temperature Spread by Season — {country_sel}",
    stripmode="overlay"
)
fig.show()

# Commented out IPython magic to ensure Python compatibility.
#  %% [markdown]
# Viz 9 — Correlation heatmap of numeric features
# Reload the original dataframe to include all numeric columns
df_full = pd.read_csv("/content/weather_data_extended.csv")
df_full.columns = [c.strip() for c in df_full.columns]

num = df_full.select_dtypes(include=[np.number]).copy()
corr = num.corr(numeric_only=True)
fig = px.imshow(corr, title="Correlation Heatmap — Weather Features")
fig.show()

if "HUMIDITY" in df.columns:
    d3 = df[df["COUNTRY"] == country_sel]
    fig = px.scatter(d3, x="HUMIDITY", y="TEMP_C",
                     color="Month",
                     title=f"Temperature vs Humidity — {country_sel}")
    fig.show()

d4 = df[df["COUNTRY"] == country_sel].copy()
d4["Month"] = d4["DATE"].dt.month
d4["Season"] = d4["Month"].map(season_from_month)

season_avg = d4.groupby("Season")["TEMP_C"].mean().reset_index()

fig = px.bar(season_avg, x="Season", y="TEMP_C",
             title=f"Average Temperature by Season — {country_sel}",
             color="TEMP_C")
fig.show()

from plotnine import ggplot, aes, geom_line, geom_point, geom_histogram, geom_smooth, geom_density, facet_wrap, labs, theme_bw, theme_minimal, theme_light, theme_classic, theme_seaborn

d2 = df[df["COUNTRY"] == country_sel].copy()

(ggplot(d2, aes(x="TEMP_C")) +
 geom_histogram(binwidth=2, fill="skyblue", color="black", alpha=0.7) +
 labs(title=f"Temperature Distribution — {country_sel}",
      x="Temperature (°C)", y="Count") +
 theme_minimal())

d3 = df[df["COUNTRY"] == country_sel].copy()#density plot

(ggplot(d3, aes(x="TEMP_C")) +
 geom_density(alpha=0.6, fill="skyblue") + # Removed fill from aes and set a constant fill color
 labs(title=f"Density Plot of Temperature — {country_sel}",
      x="Temperature (°C)", y="Density") +
 theme_light())

d4 = df[df["COUNTRY"] == country_sel].copy()#facet plot
d4["Year"] = d4["DATE"].dt.year
d4["Month"] = d4["DATE"].dt.month

(ggplot(d4, aes(x="Month", y="TEMP_C", group="Year", color="factor(Year)")) +
 geom_line(alpha=0.6) +
 facet_wrap("~Year") +
 labs(title=f"Monthly Temperature Trends by Year — {country_sel}",
      x="Month", y="Temperature (°C)") +
 theme_classic())

d5 = df[df["COUNTRY"] == country_sel].copy() #scatter +regresiion
d5["Year"] = d5["DATE"].dt.year

(ggplot(d5, aes(x="Year", y="TEMP_C")) +
 geom_point(alpha=0.4, color="dodgerblue") +
 geom_smooth(method="lm", color="red", se=True) +
 labs(title=f"Scatter with Regression Line — {country_sel}",
      x="Year", y="Temperature (°C)") +
 theme_seaborn())

